# Postgres 

version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foodprint
    ports:
      - '10432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  weaviate:
    image: semitechnologies/weaviate:1.18.3
    restart: on-failure:0
    ports:
     - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    # image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L12-v2
    environment:
      ENABLE_CUDA: 0 # set to 1 to enable
volumes:
  db:
    driver: local