/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * Cherry Pick - FoodPrint
 * FoodPrint API description
 * OpenAPI spec version: 1.0
 */

export type SourceWaterFootprintUncertainty =
  (typeof SourceWaterFootprintUncertainty)[keyof typeof SourceWaterFootprintUncertainty];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SourceWaterFootprintUncertainty = {
  L: "L",
  H: "H",
} as const;
