/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * Cherry Pick - FoodPrint
 * FoodPrint API description
 * OpenAPI spec version: 1.0
 */
import type { CreateIngridientDto } from "./createIngridientDto";

export interface CreateRecipeDto {
  description: string;
  ingredients: CreateIngridientDto[];
  name: string;
}
