/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * Cherry Pick - FoodPrint
 * FoodPrint API description
 * OpenAPI spec version: 1.0
 */
import type { Recipe } from "./recipe";
import type { Source } from "./source";

export interface Ingridient {
  calculated_carbon_footprint?: number;
  calculated_water_footprint?: number;
  createdAt: string;
  id: string;
  name: string;
  recipe: Recipe;
  source?: Source;
  updatedAt: string;
  weight: number;
}
