/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * Cherry Pick - FoodPrint
 * FoodPrint API description
 * OpenAPI spec version: 1.0
 */
import type { User } from "./user";
import type { Collection } from "./collection";
import type { RecipeComments } from "./recipeComments";
import type { RecipeFoodTagsItem } from "./recipeFoodTagsItem";
import type { RecipeIngridients } from "./recipeIngridients";

export interface Recipe {
  author: User;
  bookmarkedBy: Collection;
  calculate_carbon_footprint?: number;
  calculate_water_footprint?: number;
  comments: RecipeComments;
  createdAt: string;
  description: string;
  foodTags: RecipeFoodTagsItem[];
  id: string;
  image_url: string;
  ingridients: RecipeIngridients;
  name: string;
  updatedAt: string;
}
