/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * Cherry Pick - FoodPrint
 * FoodPrint API description
 * OpenAPI spec version: 1.0
 */

export type RecipeFoodTagsItem =
  (typeof RecipeFoodTagsItem)[keyof typeof RecipeFoodTagsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecipeFoodTagsItem = {
  High_protein: "High protein",
  Meat: "Meat",
  Fish: "Fish",
  Low_glycemic_index: "Low glycemic index",
  Rich_in_fiber: "Rich in fiber",
} as const;
