/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * Cherry Pick - FoodPrint
 * FoodPrint API description
 * OpenAPI spec version: 1.0
 */
import type { SourceCarbonFootprintUncertainty } from "./sourceCarbonFootprintUncertainty";
import type { SourceIngridients } from "./sourceIngridients";
import type { SourceWaterFootprintUncertainty } from "./sourceWaterFootprintUncertainty";

export interface Source {
  carbon_footprint?: number;
  carbon_footprint_uncertainty?: SourceCarbonFootprintUncertainty;
  createdAt: string;
  food_group: string;
  food_item: string;
  id: string;
  ingridients: SourceIngridients;
  updatedAt: string;
  water_footprint?: number;
  water_footprint_uncertainty?: SourceWaterFootprintUncertainty;
}
