/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * Cherry Pick - FoodPrint
 * FoodPrint API description
 * OpenAPI spec version: 1.0
 */
import type { UserBookmarks } from "./userBookmarks";
import type { UserComments } from "./userComments";
import type { Collection } from "./collection";
import type { UserRecipes } from "./userRecipes";

export interface User {
  bookmarks: UserBookmarks;
  comments: UserComments;
  createdAt: string;
  firstName?: string;
  followers: Collection;
  hashedPassword: string;
  id: string;
  lastName?: string;
  recipes: UserRecipes;
  socials?: string[];
  updatedAt: string;
  username: string;
}
