/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * Cherry Pick - FoodPrint
 * FoodPrint API description
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  UseMutationOptions,
  MutationFunction,
} from "@tanstack/react-query";
import { customInstance } from ".././mutator/custom-instance";
import type { ErrorType } from ".././mutator/custom-instance";

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P
) => any
  ? P
  : never;

export const devControllerSeed = (
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/dev/seed`, method: "post" },
    options
  );
};

export const getDevControllerSeedMutationOptions = <
  TError = ErrorType<unknown>,
  TVariables = void,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof devControllerSeed>>,
    TError,
    TVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof devControllerSeed>>,
  TError,
  TVariables,
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof devControllerSeed>>,
    TVariables
  > = () => {
    return devControllerSeed(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DevControllerSeedMutationResult = NonNullable<
  Awaited<ReturnType<typeof devControllerSeed>>
>;

export type DevControllerSeedMutationError = ErrorType<unknown>;

export const useDevControllerSeed = <
  TError = ErrorType<unknown>,
  TVariables = void,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof devControllerSeed>>,
    TError,
    TVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getDevControllerSeedMutationOptions(options);

  return useMutation(mutationOptions);
};
export const devControllerSeed1 = (
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/dev/seed1`, method: "post" },
    options
  );
};

export const getDevControllerSeed1MutationOptions = <
  TError = ErrorType<unknown>,
  TVariables = void,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof devControllerSeed1>>,
    TError,
    TVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof devControllerSeed1>>,
  TError,
  TVariables,
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof devControllerSeed1>>,
    TVariables
  > = () => {
    return devControllerSeed1(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DevControllerSeed1MutationResult = NonNullable<
  Awaited<ReturnType<typeof devControllerSeed1>>
>;

export type DevControllerSeed1MutationError = ErrorType<unknown>;

export const useDevControllerSeed1 = <
  TError = ErrorType<unknown>,
  TVariables = void,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof devControllerSeed1>>,
    TError,
    TVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getDevControllerSeed1MutationOptions(options);

  return useMutation(mutationOptions);
};
export const devControllerSeed2 = (
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/dev/seed2`, method: "post" },
    options
  );
};

export const getDevControllerSeed2MutationOptions = <
  TError = ErrorType<unknown>,
  TVariables = void,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof devControllerSeed2>>,
    TError,
    TVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof devControllerSeed2>>,
  TError,
  TVariables,
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof devControllerSeed2>>,
    TVariables
  > = () => {
    return devControllerSeed2(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DevControllerSeed2MutationResult = NonNullable<
  Awaited<ReturnType<typeof devControllerSeed2>>
>;

export type DevControllerSeed2MutationError = ErrorType<unknown>;

export const useDevControllerSeed2 = <
  TError = ErrorType<unknown>,
  TVariables = void,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof devControllerSeed2>>,
    TError,
    TVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getDevControllerSeed2MutationOptions(options);

  return useMutation(mutationOptions);
};
export const devControllerSeed3 = (
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/api/dev/seed3`, method: "post" },
    options
  );
};

export const getDevControllerSeed3MutationOptions = <
  TError = ErrorType<unknown>,
  TVariables = void,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof devControllerSeed3>>,
    TError,
    TVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof devControllerSeed3>>,
  TError,
  TVariables,
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof devControllerSeed3>>,
    TVariables
  > = () => {
    return devControllerSeed3(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DevControllerSeed3MutationResult = NonNullable<
  Awaited<ReturnType<typeof devControllerSeed3>>
>;

export type DevControllerSeed3MutationError = ErrorType<unknown>;

export const useDevControllerSeed3 = <
  TError = ErrorType<unknown>,
  TVariables = void,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof devControllerSeed3>>,
    TError,
    TVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationOptions = getDevControllerSeed3MutationOptions(options);

  return useMutation(mutationOptions);
};
